window.DIAGNOSTICOS = [{"c":"Taquicardias de QRS angosto","d":"Taquicardia auricular ectópica","casos":["f1c1","f4c2","f6c1","f6c9","f8c4","f9c3","f11c3","f11c6","f11c7"]},
  {"c":"Taquicardias de QRS angosto","d":"Taquicardia intrauricular reentrante","casos":["f1c2","f4c1","f10c3"]},
  {"c":"Taquicardias de QRS angosto","d":"Taquicardia por reentrada nodal (TRNAV)","casos":["f2c6","f6c2"]},
  {"c":"Taquicardias de QRS angosto","d":"Taquicardia por reentrada AV ortodrómica (vía accesoria)","casos":["f1c4","f3c8","f6c3","f6c8","f7c5","f7c7","f8c3"]},
  {"c":"Taquicardias de QRS angosto","d":"Taquicardia de Coumel","casos":["f2c10","f10c10"]},
  {"c":"Taquicardias de QRS angosto","d":"Taquicardia ectópica de la unión (JET)","casos":["f1c3","f3c7","f3c9","f6c10","f11c2","f11c5","f11c8"]},
  {"c":"Taquicardias de QRS angosto","d":"Fibrilación auricular","casos":["f8c2","f11c4"]},
  {"c":"Taquicardias de QRS ancho","d":"Taquicardia por reentrada AV antidrómica","casos":["f4c3","f6c7"]},
  {"c":"Taquicardias de QRS ancho","d":"Taquicardia por reentrada AV ortodrómica con aberrancia","casos":["f3c11","f9c4","f10c9"]},
  {"c":"Taquicardias de QRS ancho","d":"Fibrilación auricular preexcitada","casos":["f3c10","f8c7"]},
  {"c":"Taquicardias de QRS ancho","d":"Fibrilación auricular con aberrancia (fenómeno de Ashman)","casos":["f4c10"]},
  {"c":"Taquicardias de QRS ancho","d":"Taquicardia supraventricular con aberrancia","casos":["f2c3"]},
  {"c":"Taquicardias de QRS ancho","d":"Aleteo auricular con aberrancia","casos":["f11c9"]},
  {"c":"Taquicardias de QRS ancho","d":"Taquicardia ventricular monomorfa","casos":["f4c6","f5c6"]},
  {"c":"Taquicardias de QRS ancho","d":"Taquicardia ventricular fascicular posterior","casos":["f3c5"]},
  {"c":"Taquicardias de QRS ancho","d":"Taquicardia ventricular del músculo papilar posterior","casos":["f8c6"]},
  {"c":"Arritmias ventriculares","d":"Extrasístoles ventriculares del tracto de salida","casos":["f5c3","f9c6"]},
  {"c":"Arritmias ventriculares","d":"Extrasístole ventricular del anillo mitral","casos":["f5c7"]},
  {"c":"Arritmias ventriculares","d":"Ritmo idioventricular acelerado (RIVA)","casos":["f1c5","f4c5","f3c3"]},
  {"c":"Arritmias ventriculares","d":"Taquicardia ventricular polimorfa catecolaminérgica (CPVT)","casos":["f4c9"]},
  {"c":"Arritmias ventriculares","d":"Torsades de pointes","casos":["f7c2"]},
  {"c":"Taquicardia ventricular","d":"Taquicardia ventricular","casos":["f6c4","f6c5","f7c6","f10c1","f10c7"]},
  {"c":"Posoperatorio de cirugía cardíaca","d":"Arritmia en el posoperatorio","casos":["f6c9","f6c10","f7c1","f7c10","f8c9","f10c6","f11c5","f11c9"]},
  {"c":"Posoperatorio de cirugía cardíaca","d":"Arritmia en el posoperatorio alejado","casos":["f9c7","f10c3"]},
  {"c":"Miocardiopatías","d":"Miocardiopatía","casos":["f6c5","f6c7"]},
  {"c":"Extrasístoles","d":"Extrasístoles","casos":["f5c5","f10c8"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Bloqueo AV completo","casos":["f1c6","f3c1","f3c2","f3c3","f7c4","f10c2"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Bloqueo AV de segundo grado Mobitz I","casos":["f2c4","f2c5","f8c1"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Bloqueo AV 2:1 y de alto grado","casos":["f1c7","f2c4","f5c8","f8c8","f9c5"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Bloqueo","casos":["f11c1"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Bloqueo AV paroxístico","casos":["f7c3"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Pseudo-bloqueo AV 2:1 por QT largo","casos":["f2c8"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Conducción oculta / extrasístole nodal con P bloqueada","casos":["f1c10"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Trigeminia auricular bloqueada","casos":["f2c1"]},
  {"c":"Bloqueos y trastornos de conducción","d":"Doble nodo AV","casos":["f10c5"]},
  {"c":"Preexcitación","d":"Preexcitación ventricular (WPW)","casos":["f1c9","f3c4","f4c7","f5c2","f6c6","f7c7"]},
  {"c":"Canalopatías y repolarización","d":"Canalopatía","casos":["f7c6"]},
  {"c":"Canalopatías y repolarización","d":"Intervalo QT corto","casos":["f2c2"]},
  {"c":"Canalopatías y repolarización","d":"Síndrome de QT largo tipo III","casos":["f2c8"]},
  {"c":"Canalopatías y repolarización","d":"Síndrome de Andersen-Tawil (QT largo tipo VII)","casos":["f9c9"]},
  {"c":"Canalopatías y repolarización","d":"Síndrome de Brugada","casos":["f7c8","f8c3"]},
  {"c":"Canalopatías y repolarización","d":"Alteraciones del medio interno (potasio y calcio)","casos":["f2c7","f5c4","f9c8"]},
  {"c":"Canalopatías y repolarización","d":"Pericarditis aguda","casos":["f9c10"]},
  {"c":"Canalopatías y repolarización","d":"Isquemia","casos":["f9c2"]},
  {"c":"Canalopatías y repolarización","d":"Isquemia transmural","casos":["f10c4"]},
  {"c":"Canalopatías y repolarización","d":"Repolarización precoz","casos":["f3c6"]},
  {"c":"Intoxicaciones","d":"Arritmia por intoxicación (bigeminia y tripletas ventriculares polimórficas)","casos":["f8c10"]},
  {"c":"Marcapasos y dispositivos","d":"Fallas de marcapasos (sensado y captura)","casos":["f2c9","f4c4","f4c8","f5c1"]},
  {"c":"Marcapasos y dispositivos","d":"Paciente con CDI","casos":["f8c5"]},
  {"c":"Otros","d":"Arritmia asociada a quimioterapia","casos":["f9c1","f11c4","f11c10"]},
  {"c":"Otros","d":"Transposición corregida de grandes vasos (L-TGV)","casos":["f2c4","f5c9"]},
  {"c":"Otros","d":"Ritmo sinusal con conducción AV conservada","casos":["f1c8"]},
  {"c":"Otros","d":"Taquicardia sinusal","casos":["f8c9"]},
  {"c":"Otros","d":"Síncope","casos":["f7c9"]}];
