// Listado de drogas a evitar (pestaña "Drogas a evitar"). Dos listas independientes: QT largo congénito y Sme. de Brugada.
// items de "qt": [nombre genérico, nombres comerciales, código de riesgo]. Código según CredibleMeds (ver DROGAS.qt.categorias).
window.DROGAS = {
  qt: {
    titulo: 'Medicamentos a evitar en QT largo congénito',
    fuente: 'CredibleMeds.org (AZCERT, Inc.) — lista "Medicamentos que deben evitar pacientes con QT prolongado congénito". Generado: 6 de febrero de 2025 · Última revisión de la lista: 2 de diciembre de 2024. La lista cambia regularmente: para la versión más actualizada, consultar crediblemeds.org.',
    aviso: 'La ausencia de un medicamento en esta lista no significa que esté libre de riesgo de prolongar el QT o de Torsión de Puntas: muchos fármacos no fueron evaluados para ese riesgo, especialmente en pacientes con QT largo congénito. Herramienta de apoyo: no reemplaza el juicio clínico ni la consulta de la fuente original.',
    categorias: {
      KR: 'Riesgo conocido de Torsión de Puntas',
      PR: 'Riesgo posible de Torsión de Puntas',
      CR: 'Riesgo condicional de Torsión de Puntas (p. ej. en sobredosis, con hipopotasemia/hipomagnesemia, bradicardia o por interacción con otros fármacos)',
      SR: 'Riesgo especial en QT largo congénito (no necesariamente asociado a riesgo de Torsión de Puntas en la población general)'
    },
    items: [
      ['Abarelix', 'Plenaxis', 'PR'],
      ['Abiraterone', 'Zytiga y otros', 'CR'],
      ['Aclarubicin', 'Aclacin y otros', 'KR'],
      ['Adagrasib', 'Krazati', 'PR'],
      ['Albuterol (salbutamol)', 'Proventil y otros', 'SR'],
      ['Alfuzosin', 'Uroxatral', 'PR'],
      ['Alimemazine (Trimeprazine)', 'Nedeltran y otros', 'PR'],
      ['Amantadine', 'Symmetrel y otros', 'CR'],
      ['Amiodarone', 'Cordarone y otros', 'KR'],
      ['Amisulpride', 'Barhemsys y otros', 'CR'],
      ['Amitriptyline', 'Elavil (discontinuado) y otros', 'CR'],
      ['Amphetamine (Amfetamine)', 'Adderal-XR y otros', 'SR'],
      ['Amphotericin B', 'Fungilin y otros', 'CR'],
      ['Amsacrine (Acridinyl anisidide)', 'Amsidine', 'CR'],
      ['Anagrelide', 'Agrylin y otros', 'KR'],
      ['Apalutamide', 'Erleada', 'PR'],
      ['Apomorphine', 'Apokyn y otros', 'PR'],
      ['Arformoterol', 'Brovana', 'SR'],
      ['Aripiprazole', 'Abilify y otros', 'PR'],
      ['Arsenic trioxide', 'Trisenox', 'KR'],
      ['Artemether/Lumefantrine', 'Coartem', 'PR'],
      ['Artenimol/piperaquine', 'Eurartesim', 'PR'],
      ['Asenapine', 'Saphris y otros', 'PR'],
      ['Astemizole', 'Hismanal', 'KR'],
      ['Atazanavir', 'Reyataz y otros', 'CR'],
      ['Atomoxetine', 'Strattera', 'PR'],
      ['Azithromycin', 'Zithromax y otros', 'KR'],
      ['Bedaquiline', 'Sirturo', 'PR'],
      ['Bendamustine', 'Treanda y otros', 'PR'],
      ['Bendroflumethiazide (Bendrofluazide)', 'Aprinox y otros', 'CR'],
      ['Benzphetamine', 'Didrex y otros', 'SR'],
      ['Bepridil', 'Vascor', 'KR'],
      ['Betrixaban', 'Bevyxxa', 'PR'],
      ['Bicalutamide', 'Casodex', 'PR'],
      ['Bortezomib (Bortexomib)', 'Velcade y otros', 'PR'],
      ['Bosutinib', 'Bosulif', 'PR'],
      ['Buprenorphine', 'Butrans y otros', 'PR'],
      ['Cabozantinib', 'Cometriq', 'PR'],
      ['Capecitabine', 'Xeloda', 'PR'],
      ['Carbetocin', 'Pabal y otros', 'PR'],
      ['Ceritinib', 'Zykadia', 'PR'],
      ['Cesium Chloride', 'Energy Catalyst', 'KR'],
      ['Chloral hydrate', 'Aquachloral y otros', 'CR'],
      ['Chloroquine', 'Aralen', 'KR'],
      ['Chlorpromazine', 'Thorazine y otros', 'KR'],
      ['Chlorprothixene', 'Truxal', 'KR'],
      ['Cilostazol', 'Pletal', 'KR'],
      ['Cimetidine', 'Tagamet', 'CR'],
      ['Ciprofloxacin', 'Cipro y otros', 'KR'],
      ['Cisapride', 'Propulsid', 'KR'],
      ['Citalopram', 'Celexa y otros', 'KR'],
      ['Clarithromycin', 'Biaxin y otros', 'KR'],
      ['Clofazimine', 'Lamprene', 'CR'],
      ['Clomipramine', 'Anafranil', 'CR'],
      ['Clotiapine', 'Entumine', 'PR'],
      ['Clozapine', 'Clozaril y otros', 'PR'],
      ['Cobimetinib', 'Cotellic', 'PR'],
      ['Cocaine', 'Cocaína', 'KR'],
      ['Crizotinib', 'Xalkori', 'PR'],
      ['Cyamemazine (Cyamepromazine)', 'Tercian', 'PR'],
      ['Dabrafenib', 'Tafinlar', 'PR'],
      ['Dasatinib', 'Sprycel', 'PR'],
      ['Degarelix', 'Firmagon y otros', 'PR'],
      ['Delamanid', 'Deltyba', 'PR'],
      ['Desipramine', 'Pertofrane y otros', 'PR'],
      ['Dexmedetomidine', 'Precedex y otros', 'PR'],
      ['Dexmethylphenidate', 'Focalin y otros', 'SR'],
      ['Dextroamphetamine (Dexamfetamine)', 'Dexedrine y otros', 'SR'],
      ['Dextromethorphan/Quinidine', 'Nuedexta', 'PR'],
      ['Diethylpropion (amfepramone)', 'Tenuate y otros', 'SR'],
      ['Diltiazem', 'Cardizem', 'CR'],
      ['Diphenhydramine', 'Benadryl y otros', 'CR'],
      ['Disopyramide', 'Norpace', 'KR'],
      ['Dobutamine', 'Dobutrex', 'SR'],
      ['Dofetilide', 'Tikosyn', 'KR'],
      ['Dolasetron', 'Anzemet', 'PR'],
      ['Domperidone', 'Motilium y otros', 'KR'],
      ['Donepezil', 'Aricept', 'KR'],
      ['Dopamine', 'Intropine', 'SR'],
      ['Doxepin', 'Sinequan y otros', 'CR'],
      ['Dronedarone', 'Multaq', 'KR'],
      ['Droperidol', 'Inapsine y otros', 'KR'],
      ['Droxidopa', 'Northera', 'SR'],
      ['Efavirenz', 'Sustiva', 'PR'],
      ['Eliglustat', 'Cerdelga', 'PR'],
      ['Encorafenib', 'Braftovi', 'PR'],
      ['Entrectinib', 'Rozlytrek', 'PR'],
      ['Eperisone', 'Myonal y otros', 'CR'],
      ['Ephedrine', 'Rynatuss y otros', 'SR'],
      ['Epinephrine (Adrenaline)', 'Primatene y otros', 'SR'],
      ['Epirubicin', 'Ellence y otros', 'PR'],
      ['Eribulin mesylate', 'Halaven', 'PR'],
      ['Erythromycin', 'E.E.S. y otros', 'KR'],
      ['Escitalopram', 'Cipralex y otros', 'KR'],
      ['Esomeprazole', 'Nexium y otros', 'CR'],
      ['Ezogabine (Retigabine)', 'Potiga y otros', 'PR'],
      ['Famotidine', 'Pepcid y otros', 'CR'],
      ['Felbamate', 'Felbatol', 'PR'],
      ['Fenfluramine', 'Fintepla', 'SR'],
      ['Fenoterol', 'Berotec y otros', 'SR'],
      ['Fexinidazole', 'Fexinidazole', 'PR'],
      ['Fingolimod', 'Gilenya', 'PR'],
      ['Flecainide', 'Tambocor y otros', 'KR'],
      ['Fluconazole', 'Diflucan y otros', 'KR'],
      ['Fluorouracil (5-FU)', 'Adrucil y otros', 'PR'],
      ['Fluoxetine', 'Prozac y otros', 'CR'],
      ['Flupentixol', 'Depixol y otros', 'PR'],
      ['Fluticasone And Salmeterol', 'Advair y otros', 'SR'],
      ['Fluvoxamine', 'Faverin y otros', 'CR'],
      ['Formoterol', 'Foradil y otros', 'SR'],
      ['Furosemide (frusemide)', 'Lasix y otros', 'CR'],
      ['Galantamine', 'Reminyl y otros', 'CR'],
      ['Garenoxacin', 'Geninax', 'CR'],
      ['Gatifloxacin', 'Tequin', 'KR'],
      ['Gemifloxacin', 'Factive', 'PR'],
      ['Gepirone', 'Exxua', 'PR'],
      ['Gilteritinib', 'Xospata', 'PR'],
      ['Givinostat', 'Duvyzat', 'PR'],
      ['Glasdegib', 'Daurismo', 'PR'],
      ['Granisetron', 'Kytril y otros', 'PR'],
      ['Grepafloxacin', 'Raxar', 'KR'],
      ['Halofantrine', 'Halfan', 'KR'],
      ['Haloperidol', 'Haldol y otros', 'KR'],
      ['Hydrochlorothiazide', 'Apo-Hydro y otros', 'CR'],
      ['Hydrocodone - ER', 'Hysingla ER y otros', 'PR'],
      ['Hydroquinidine (Dihydroquinidine)', 'Serecor', 'KR'],
      ['Hydroxychloroquine', 'Plaquenil y otros', 'KR'],
      ['Hydroxyzine', 'Atarax y otros', 'CR'],
      ['Ibogaine', '', 'KR'],
      ['Ibutilide', 'Corvert', 'KR'],
      ['Iloperidone', 'Fanapt y otros', 'PR'],
      ['Imatinib', 'Gleevec y otros', 'PR'],
      ['Imipramine (Melipramine)', 'Tofranil', 'PR'],
      ['Indacaterol', 'Arcapta Neohaler y otros', 'SR'],
      ['Indapamide', 'Lozol y otros', 'CR'],
      ['Inotuzumab ozogamicin', 'Besponsa', 'PR'],
      ['Isoflurane', 'Forane', 'PR'],
      ['Isoproterenol (isoprenaline)', 'Medihaler-Iso y otros', 'SR'],
      ['Isradipine', 'Dynacirc', 'PR'],
      ['Itraconazole', 'Sporanox y otros', 'CR'],
      ['Ivabradine', 'Procoralan y otros', 'KR'],
      ['Ivosidenib', 'Tibsovo', 'PR'],
      ['Ketanserin', 'Sufrexal', 'PR'],
      ['Ketoconazole', 'Nizoral y otros', 'CR'],
      ['Lacidipine', 'Lacipil y otros', 'PR'],
      ['Lansoprazole', 'Prevacid y otros', 'CR'],
      ['Lapatinib', 'Tykerb y otros', 'PR'],
      ['Lefamulin', 'Xenleta', 'PR'],
      ['Lenvatinib', 'Lenvima', 'PR'],
      ['Leuprolide (Leuprorelin)', 'Lupron y otros', 'PR'],
      ['Levalbuterol (Levsalbutamol)', 'Xopenex y otros', 'SR'],
      ['Levofloxacin', 'Levaquin y otros', 'KR'],
      ['Levoketoconazole', 'Recorlev', 'PR'],
      ['Levomepromazine (Methotrimeprazine)', 'Nosinan y otros', 'KR'],
      ['Levomethadone (levamethadone)', '', 'PR'],
      ['Levomethadyl acetate', 'Orlaam', 'KR'],
      ['Levomethamphetamine (Levmetamfetamine)', 'Sinu Inhaler y otros', 'SR'],
      ['Levosulpiride', 'Lesuride y otros', 'KR'],
      ['Lisdexamfetamine', 'Vyvanse', 'SR'],
      ['Lithium', 'Eskalith y otros', 'PR'],
      ['Lofexidine', 'Lucemyra', 'PR'],
      ['Loperamide', 'Imodium', 'CR'],
      ['Lopinavir/Ritonavir', 'Kaletra y otros', 'PR'],
      ['Lumateperone', 'Caplyta', 'PR'],
      ['Lurasidone', 'Latuda', 'PR'],
      ['Macimorelin', 'Macrilen', 'PR'],
      ['Maprotiline', 'Ludiomil', 'PR'],
      ['Mavorixafor', 'Xolremdi', 'PR'],
      ['Meglumine antimoniate', 'Glucantime', 'KR'],
      ['Melperone', 'Bunil y otros', 'PR'],
      ['Mesoridazine', 'Serentil', 'KR'],
      ['Metaproterenol (Orciprenaline)', 'Metaprel y otros', 'SR'],
      ['Methadone', 'Dolophine y otros', 'KR'],
      ['Methamphetamine (Metamfetamine)', 'Desoxyn y otros', 'SR'],
      ['Methylphenidate', 'Ritalin y otros', 'SR'],
      ['Metoclopramide', 'Reglan y otros', 'CR'],
      ['Metolazone', 'Zytanix y otros', 'CR'],
      ['Metronidazole', 'Flagyl y otros', 'CR'],
      ['Mianserin', 'Tolvon', 'PR'],
      ['Midodrine', 'ProAmatine y otros', 'SR'],
      ['Midostaurin', 'Rydapt', 'PR'],
      ['Mifepristone', 'Korlym y otros', 'PR'],
      ['Mirabegron', 'Myrbetriq', 'PR'],
      ['Mirtazapine', 'Remeron', 'PR'],
      ['Mobocertinib', 'Exkivity', 'KR'],
      ['Moclobemide', 'Amira y otros', 'PR'],
      ['Motixafortide', 'Aphexda', 'PR'],
      ['Moxifloxacin', 'Avelox y otros', 'KR'],
      ['Necitumumab', 'Portrazza', 'PR'],
      ['Nelfinavir', 'Viracept', 'CR'],
      ['Nicardipine', 'Cardene', 'PR'],
      ['Nifekalant', 'Shinbit', 'KR'],
      ['Nilotinib', 'Tasigna', 'PR'],
      ['Norepinephrine', 'Levophed', 'SR'],
      ['Norfloxacin', 'Noroxin y otros', 'PR'],
      ['Nortriptyline', 'Pamelor y otros', 'PR'],
      ['Nusinersen', 'Spinraza', 'PR'],
      ['Ofloxacin', 'Floxin', 'PR'],
      ['Olanzapine', 'Zyprexa y otros', 'CR'],
      ['Oliceridine', 'Olinvyk', 'PR'],
      ['Olodaterol', 'Striverdi Respimat', 'SR'],
      ['Omeprazole', 'Losec y otros', 'CR'],
      ['Ondansetron', 'Zofran y otros', 'KR'],
      ['Opipramol', 'Deprenil y otros', 'PR'],
      ['Osilodrostat', 'Isturisa', 'PR'],
      ['Osimertinib', 'Tagrisso', 'KR'],
      ['Oxaliplatin', 'Eloxatin', 'KR'],
      ['Oxymetazoline', 'Afrin y otros', 'SR'],
      ['Oxytocin', 'Pitocin y otros', 'PR'],
      ['Ozanimod', 'Zeposia', 'PR'],
      ['Pacritinib', 'Vonjo', 'PR'],
      ['Paliperidone', 'Invega y otros', 'PR'],
      ['Palonosetron', 'Aloxi', 'PR'],
      ['Panobinostat', 'Farydak', 'PR'],
      ['Pantoprazole', 'Protonix y otros', 'CR'],
      ['Papaverine HCl (Intracoronario)', 'ParaTime SR y otros', 'KR'],
      ['Paroxetine', 'Paxil y otros', 'CR'],
      ['Pasireotide', 'Signifor', 'PR'],
      ['Pazopanib', 'Votrient', 'PR'],
      ['Pentamidine', 'Pentam', 'KR'],
      ['Perphenazine', 'Trilafon y otros', 'PR'],
      ['Phendimetrazine', 'Bontril y otros', 'SR'],
      ['Phentermine', 'Adipex P y otros', 'SR'],
      ['Phenylephrine', 'Neosynephrine', 'SR'],
      ['Phenylpropanolamine', 'Acutrim y otros', 'SR'],
      ['Pilsicainide', 'Sunrythm', 'PR'],
      ['Pimavanserin', 'Nuplazid', 'PR'],
      ['Pimozide', 'Orap', 'KR'],
      ['Pipamperone', 'Dipiperon y otros', 'PR'],
      ['Piperacillin/Tazobactam', 'Tazosyn y otros', 'CR'],
      ['Pitolisant (Tiprolisant)', 'Wakix', 'PR'],
      ['Ponesimod', 'Ponvory', 'PR'],
      ['Posaconazole', 'Noxafil y otros', 'CR'],
      ['Pralsetinib', 'Gavreto', 'PR'],
      ['Pretomanid', 'Dovprela', 'PR'],
      ['Primaquine phosphate', 'Jasoprim y otros', 'PR'],
      ['Probucol', 'Lorelco', 'KR'],
      ['Procainamide', 'Pronestyl y otros', 'KR'],
      ['Promethazine', 'Phenergan', 'PR'],
      ['Propafenone', 'Rythmol SR y otros', 'CR'],
      ['Propofol', 'Diprivan y otros', 'KR'],
      ['Prothipendyl', 'Dominal y otros', 'PR'],
      ['Pseudoephedrine', 'PediaCare y otros', 'SR'],
      ['Quetiapine', 'Seroquel', 'CR'],
      ['Quinidine', 'Quinaglute y otros', 'KR'],
      ['Quinine sulfate', 'Qualaquin y otros', 'CR'],
      ['Quizartinib', 'Vanflyta', 'KR'],
      ['Ranolazine', 'Ranexa y otros', 'CR'],
      ['Relugolix', 'Orgovyx y otros', 'PR'],
      ['Remdesivir', 'Veklury', 'PR'],
      ['Remimazolam', 'Byfavo', 'PR'],
      ['Revumenib', 'Revuforj', 'PR'],
      ['Ribociclib', 'Kisqali', 'PR'],
      ['Rilpivirine', 'Edurant y otros', 'PR'],
      ['Risperidone', 'Risperdal', 'CR'],
      ['Ritodrine', 'Yutopar', 'SR'],
      ['Rivastigmine', 'Exelon', 'PR'],
      ['Romidepsin', 'Istodax', 'PR'],
      ['Roxithromycin', 'Rulide y otros', 'KR'],
      ['Rucaparib', 'Rubraca', 'PR'],
      ['Salmeterol', 'Serevent y otros', 'SR'],
      ['Saquinavir (con ritonavir)', 'Invirase', 'PR'],
      ['Selpercatinib', 'Retevmo', 'PR'],
      ['Serdexmethylphenidate', 'Azstarys', 'SR'],
      ['Sertindole', 'Serdolect y otros', 'KR'],
      ['Sertraline', 'Zoloft y otros', 'CR'],
      ['Sevoflurane', 'Ultane y otros', 'KR'],
      ['Sibutramine', 'Meridia', 'SR'],
      ['Siponimod', 'Mayzent', 'PR'],
      ['Sitafloxacin', 'Gracevit', 'PR'],
      ['Solifenacin', 'Vesicare', 'CR'],
      ['Sorafenib', 'Nexavar', 'PR'],
      ['Sotalol', 'Betapace y otros', 'KR'],
      ['Sparfloxacin', 'Zagam', 'KR'],
      ['Sulfamethoxazole y Trimethoprim', 'Septra y otros', 'SR'],
      ['Sulpiride', 'Dogmatil y otros', 'KR'],
      ['Sultopride', 'Barnetil y otros', 'KR'],
      ['Sunitinib', 'Sutent', 'PR'],
      ['Tacrolimus', 'Prograf y otros', 'PR'],
      ['Tamoxifen', 'Nolvadex y otros', 'PR'],
      ['Tazemetostat', 'Tazverik', 'PR'],
      ['Tebentafusp', 'Kimmtrak', 'PR'],
      ['Telaprevir', 'Incivo y otros', 'CR'],
      ['Telavancin', 'Vibativ', 'PR'],
      ['Telithromycin', 'Ketek', 'PR'],
      ['Terbutaline', 'Brethine y otros', 'SR'],
      ['Terfenadine', 'Seldane', 'KR'],
      ['Terlipressin', 'Teripress y otros', 'KR'],
      ['Terodiline', 'Micturin y otros', 'KR'],
      ['Tetrabenazine', 'Nitoman y otros', 'PR'],
      ['Thioridazine', 'Mellaril y otros', 'KR'],
      ['Tiapride', 'Tiapridal y otros', 'PR'],
      ['Tipiracil/Trifluridine', 'Lonsurf', 'PR'],
      ['Tizanidine', 'Zanaflex y otros', 'PR'],
      ['Tolterodine', 'Detrol y otros', 'PR'],
      ['Toremifene', 'Fareston', 'PR'],
      ['Torsemide (Torasemide)', 'Demadex y otros', 'CR'],
      ['Tramadol', 'Crispin y otros', 'PR'],
      ['Trazodone', 'Desyrel y otros', 'CR'],
      ['Triclabendazole', 'Egaten', 'PR'],
      ['Trimipramine', 'Surmontil y otros', 'PR'],
      ['Tropisetron', 'Navoban y otros', 'PR'],
      ['Valbenazine', 'Ingrezza', 'PR'],
      ['Vandetanib', 'Caprelsa', 'KR'],
      ['Vardenafil', 'Levitra', 'PR'],
      ['Vemurafenib', 'Zelboraf', 'PR'],
      ['Venlafaxine', 'Effexor y otros', 'PR'],
      ['Vernakalant', 'Brinavess y otros', 'PR'],
      ['Vilanterol/fluticasone furoate', 'Breo Ellipta', 'SR'],
      ['Voclosporin', 'Lupkynis', 'PR'],
      ['Voriconazole', 'VFend', 'CR'],
      ['Vorinostat', 'Zolinza', 'PR'],
      ['Xylometazoline (Xylomethazoline)', 'Sinosil y otros', 'SR'],
      ['Ziprasidone', 'Geodon y otros', 'CR'],
      ['Zotepine', 'Losizopilon y otros', 'PR'],
      ['Zuclopenthixol (Zuclopentixol)', 'Cisordinol y otros', 'PR']
    ]
  },
  brugada: {
    titulo: 'Medicamentos a evitar en síndrome de Brugada',
    fuente: 'Adaptado de la lista de medicamentos a evitar en síndrome de Brugada (basada en las guías publicadas y mantenida por el registro internacional de Brugada / BrugadaDrugs.org).',
    clases: {
      I: 'Evidencia/opinión convincente',
      IIa: 'Evidencia/opinión menos clara',
      IIb: 'Evidencia/opinión contradictoria',
      III: 'Muy poca evidencia'
    },
    grupos: [
      {
        t: 'Drogas antiarrítmicas',
        items: [
          { g: 'Ajmalina', m: 'Gilurytmal®', uso: 'Antiarrítmico (Clase 1A: bloqueador de Na)', clase: 'I' },
          { g: 'Allapinin', m: 'Allapinine®, Glialin®, Lappaconite Hydrobromide®', uso: 'Antiarrítmico (Clase 1C: bloqueador de Na)', clase: 'IIb' },
          { g: 'Etacizina', m: 'Ethacizine®, Etacizin®, Etmozin®', uso: 'Antiarrítmico (Clase 1C: bloqueador de Na)', clase: 'IIb' },
          { g: 'Flecainida', m: 'Tambocor®', uso: 'Antiarrítmico (Clase 1C: bloqueador de Na)', clase: 'I' },
          { g: 'Pilsicainida', m: 'Sunrhythm®', uso: 'Antiarrítmico (Clase 1C: bloqueador de Na)', clase: 'I' },
          { g: 'Procainamida', m: 'Procan®, Pronestyl®', uso: 'Antiarrítmico (Clase 1A: bloqueador de Na)', clase: 'I' },
          { g: 'Propafenona', m: 'Rythmol®', uso: 'Antiarrítmico (Clase 1C: bloqueador de Na)', clase: 'IIa' }
        ]
      },
      {
        t: 'Drogas sicotrópicas',
        items: [
          { g: 'Amitriptilina', m: 'Elavil®, Sarotex®, Tryptizol®', uso: 'Antidepresivo (tricíclico)', clase: 'IIa' },
          { g: 'Clomipramina', m: 'Anafranil®, Anafril®', uso: 'Antidepresivo (tricíclico)', clase: 'IIa' },
          { g: 'Desipramina', m: 'Norpramin®, Pentofran®', uso: 'Antidepresivo (tricíclico)', clase: 'IIa' },
          { g: 'Litio', m: 'Eskalith®', uso: 'Antidepresivo', clase: 'IIb' },
          { g: 'Loxapina', m: 'Cloxazepine®, Loxitane®', uso: 'Antipsicótico', clase: 'IIa' },
          { g: 'Nortriptilina', m: 'Nortrilen®, Pamelor®', uso: 'Antidepresivo (tricíclico)', clase: 'IIa' },
          { g: 'Oxcarbazepina', m: 'Trileptal®', uso: 'Antiepiléptico', clase: 'IIa', nota: 'Es un derivado estructural de la carbamazepina, que está en la lista de fármacos a evitar preferentemente.' },
          { g: 'Trifluoperazina', m: 'Fluoperazine®, Stelazine®', uso: 'Antipsicótico (fenotiazina)', clase: 'IIa' }
        ]
      },
      {
        t: 'Anestésicos / analgésicos',
        items: [
          { g: 'Bupivacaína', m: 'Marcaine®, Sensorcaine®', uso: 'Anestésico / analgésico', clase: 'IIa' },
          { g: 'Procaína', m: 'Procaine-Penicillin, Novocain®', uso: 'Analgésico', clase: 'IIa' },
          { g: 'Propofol', m: 'Diprivan®', uso: 'Anestésico', clase: 'IIa', nota: 'La infusión prolongada se asoció particularmente con efectos adversos. Con las precauciones adecuadas, la anestesia general con propofol suele poder realizarse de forma segura.' }
        ]
      },
      {
        t: 'Otras sustancias',
        items: [
          { g: 'Acetilcolina', uso: 'Colinérgico / vasoespástico intracoronario', clase: 'IIa' },
          { g: 'Alcohol', uso: 'Sobredosis / bebida', clase: 'IIb' },
          { g: 'Cannabis', uso: 'Sustancia recreativa / droga ilícita', clase: 'IIb' },
          { g: 'Cocaína', uso: 'Droga ilícita / anestésico', clase: 'IIa' },
          { g: 'Ergonovina', uso: 'Vasoespástico intracoronario (ej. Ergotrate®)', clase: 'IIb' }
        ]
      }
    ]
  }
};
